"""Calculate the amount of dipoles needed for a given mantle volume percentage and at a desired \'thickness\'.
rootsolver function generated by AI.
"""

import numpy as np

mantle_percentage = 0.3
mantle_thickness = 1


# the equation is not entirely trivial, its cubic. had gemini write me a function
def solve_r1(x, y):
    """Solves the equation (r1 + x)^3 = r1^3 * (1 + y) for r1.

    Args:
      x: A numerical value.
      y: A numerical value.

    Returns:
      A list of solutions for r1.
    """

    # Expand the left side of the equation.
    # r1^3 + 3*r1^2*x + 3*r1*x^2 + x^3 = r1^3*(1+y)
    # r1^3 + 3*r1^2*x + 3*r1*x^2 + x^3 = r1^3 + r1^3*y
    # 0 = r1^3*y - 3*r1^2*x - 3*r1*x^2 - x^3

    # Rearrange into a cubic equation:
    # y*r1^3 - 3*x*r1^2 - 3*x^2*r1 - x^3 = 0

    coeffs = [y, -3 * x, -3 * x**2, -(x**3)]

    # Solve the cubic equation.
    roots = np.roots(coeffs)
    # I only want the real solutions (and theres only one)
    realroot = [r for r in roots.tolist() if r.imag == 0][0]

    return realroot.real


r_1 = solve_r1(mantle_thickness, mantle_percentage)
volume_core = 4 / 3 * np.pi * r_1**3
print(
    f"mantle percentage of {mantle_percentage*100}% gives r_1={int(r_1)} and core volume={int(volume_core)}"
)

# check if my math is right:
volume_full = 4 / 3 * np.pi * (r_1 + mantle_thickness) ** 3
volume_mantle = volume_full - volume_core
vol_percent_calc = volume_mantle / volume_core * 100
print(f"Check: this gives volume percentage of {vol_percent_calc}%")
